{{- range $host := .Values.certificates.hosts }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-{{ $host.hostname | replace "." "-" }}
spec:
  secretName: {{ $.Release.Name }}-{{ $host.hostname | replace "." "-" }}-tls
  dnsNames:
  - {{ $host.hostname }}
  issuerRef:
    name: {{ $.Values.certificates.issuer }}
    kind: ClusterIssuer  # or Issuer, depending on your setup
{{- end }}
