apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-klaud-cert
  namespace: default
spec:
  secretName: hello-klaud-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days before expiry
  subject:
    organizations:
      - Klaud Online
  commonName:  {{.Values.hostname }}
  dnsNames:
    -  {{.Values.hostname }}
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer