---
apiVersion: v1
kind: Service
metadata:
  name: appsec
spec:
  selector:
    app: appsec
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443  # Match the containerPort of the deployed pod
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80   # Match the containerPort of the deployed pod
    - protocol: TCP
      port: 8117
      name: health-check
      targetPort: 8117  # Match the containerPort of the deployed pod
  type: LoadBalancer